/**
 * Canvas-based winner certificate generator.
 * Renders a decorative certificate and exports as PNG.
 */

import { version } from '../../package.json';

const CERT_WIDTH = 1200;
const CERT_HEIGHT = 850;

/**
 * Draw a single certificate to a canvas and return it.
 */
export function renderCertificate({ raffleName, winnerName, prizeName, witnesses, date }) {
  const canvas = document.createElement('canvas');
  canvas.width = CERT_WIDTH;
  canvas.height = CERT_HEIGHT;
  const ctx = canvas.getContext('2d');

  // Background
  ctx.fillStyle = '#0f0f2a';
  ctx.fillRect(0, 0, CERT_WIDTH, CERT_HEIGHT);

  // Inner background
  ctx.fillStyle = '#151535';
  ctx.fillRect(30, 30, CERT_WIDTH - 60, CERT_HEIGHT - 60);

  // Gold border (double line)
  ctx.strokeStyle = '#FFD700';
  ctx.lineWidth = 4;
  ctx.strokeRect(20, 20, CERT_WIDTH - 40, CERT_HEIGHT - 40);
  ctx.strokeStyle = '#FFD70088';
  ctx.lineWidth = 2;
  ctx.strokeRect(40, 40, CERT_WIDTH - 80, CERT_HEIGHT - 80);

  // Corner decorations
  drawCornerStar(ctx, 55, 55);
  drawCornerStar(ctx, CERT_WIDTH - 55, 55);
  drawCornerStar(ctx, 55, CERT_HEIGHT - 55);
  drawCornerStar(ctx, CERT_WIDTH - 55, CERT_HEIGHT - 55);

  const cx = CERT_WIDTH / 2;
  const hasWitnesses = witnesses && witnesses.length > 0;

  // Raffle name (header)
  ctx.fillStyle = '#FFD700';
  ctx.font = 'bold 28px "Bungee", "Arial Black", Impact, sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(raffleName.toUpperCase(), cx, 100);

  // Decorative divider
  drawDivider(ctx, cx, 140, 300);

  // "Certificate of Winning"
  ctx.fillStyle = '#FFFFFF';
  ctx.font = '20px "Bungee", "Arial Black", Impact, sans-serif';
  ctx.fillText('CERTIFICATE OF WINNING', cx, 185);

  // "This certifies that"
  ctx.fillStyle = '#9090a8';
  ctx.font = '18px "Nunito", -apple-system, "Segoe UI", Roboto, sans-serif';
  ctx.fillText('This certifies that', cx, 250);

  // Winner name (large, gold)
  ctx.fillStyle = '#FFD700';
  ctx.font = 'bold 52px "Bungee", "Arial Black", Impact, sans-serif';
  let displayName = winnerName;
  while (ctx.measureText(displayName).width > CERT_WIDTH - 160 && displayName.length > 3) {
    displayName = displayName.slice(0, -4) + '...';
  }
  ctx.fillText(displayName, cx, 320);

  // Decorative divider
  drawDivider(ctx, cx, 360, 200);

  // "has won"
  ctx.fillStyle = '#9090a8';
  ctx.font = '18px "Nunito", -apple-system, "Segoe UI", Roboto, sans-serif';
  ctx.fillText('has won', cx, 400);

  // Prize name (large, pink)
  ctx.fillStyle = '#FF2D78';
  ctx.font = 'bold 40px "Bungee", "Arial Black", Impact, sans-serif';
  let displayPrize = prizeName;
  while (ctx.measureText(displayPrize).width > CERT_WIDTH - 160 && displayPrize.length > 3) {
    displayPrize = displayPrize.slice(0, -4) + '...';
  }
  ctx.fillText(displayPrize, cx, 465);

  // Decorative divider
  drawDivider(ctx, cx, 510, 300);

  // Stars decoration
  ctx.fillStyle = '#FFD700';
  ctx.font = '24px sans-serif';
  ctx.fillText('\u2605  \u2605  \u2605', cx, 555);

  // Date
  ctx.fillStyle = '#9090a8';
  ctx.font = '16px "Nunito", -apple-system, "Segoe UI", Roboto, sans-serif';
  const dateStr = new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  ctx.fillText(dateStr, cx, 600);

  // Witnesses
  if (hasWitnesses) {
    const witnessY = 660;

    ctx.fillStyle = '#9090a8';
    ctx.font = '14px "Nunito", -apple-system, "Segoe UI", Roboto, sans-serif';
    ctx.fillText('Witnessed by:', cx, witnessY);

    ctx.fillStyle = '#FFFFFF';
    ctx.font = '18px "Nunito", -apple-system, "Segoe UI", Roboto, sans-serif';

    if (witnesses.length === 1) {
      ctx.fillText(witnesses[0], cx, witnessY + 30);
      // Signature line
      drawSignatureLine(ctx, cx, witnessY + 50, 200);
    } else {
      // Two witnesses side by side
      const leftX = CERT_WIDTH * 0.3;
      const rightX = CERT_WIDTH * 0.7;

      ctx.fillText(witnesses[0], leftX, witnessY + 30);
      drawSignatureLine(ctx, leftX, witnessY + 50, 200);

      ctx.fillText(witnesses[1], rightX, witnessY + 30);
      drawSignatureLine(ctx, rightX, witnessY + 50, 200);
    }
  }

  // Footer text
  ctx.fillStyle = '#444466';
  ctx.font = '12px "Nunito", -apple-system, "Segoe UI", Roboto, sans-serif';
  ctx.fillText(`Generated by Jonathan's Raffle Winner Picker v${version}`, cx, CERT_HEIGHT - 60);

  return canvas;
}

function drawCornerStar(ctx, x, y) {
  ctx.save();
  ctx.fillStyle = '#FFD700';
  ctx.font = '20px sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText('\u2605', x, y);
  ctx.restore();
}

function drawDivider(ctx, x, y, width) {
  ctx.save();
  ctx.strokeStyle = '#FFD70066';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(x - width / 2, y);
  ctx.lineTo(x + width / 2, y);
  ctx.stroke();

  // Center diamond
  ctx.fillStyle = '#FFD700';
  ctx.beginPath();
  ctx.moveTo(x, y - 4);
  ctx.lineTo(x + 4, y);
  ctx.lineTo(x, y + 4);
  ctx.lineTo(x - 4, y);
  ctx.closePath();
  ctx.fill();
  ctx.restore();
}

function drawSignatureLine(ctx, x, y, width) {
  ctx.save();
  ctx.strokeStyle = '#FFD70044';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(x - width / 2, y);
  ctx.lineTo(x + width / 2, y);
  ctx.stroke();
  ctx.restore();
}

/**
 * Download a certificate as PNG.
 */
export function downloadCertificate({ raffleName, winnerName, prizeName, witnesses, date }) {
  const canvas = renderCertificate({ raffleName, winnerName, prizeName, witnesses, date });
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `certificate-${winnerName.replace(/[^a-zA-Z0-9]/g, '_')}.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 'image/png');
}

/**
 * Download all certificates.
 */
export function downloadAllCertificates(raffleName, winners, witnesses) {
  winners.forEach((w, i) => {
    // Stagger downloads to avoid browser blocking
    setTimeout(() => {
      downloadCertificate({
        raffleName,
        winnerName: w.name,
        prizeName: w.prize,
        witnesses: witnesses || [],
        date: w.timestamp,
      });
    }, i * 500);
  });
}
