/**
 * Canvas-based winner certificate generator.
 * Renders a decorative certificate and exports as PNG.
 */

const CERT_WIDTH = 1200;
const CERT_HEIGHT = 850;

/**
 * Draw a single certificate to a canvas and return it.
 */
export function renderCertificate({ raffleName, winnerName, prizeName, date }) {
  const canvas = document.createElement('canvas');
  canvas.width = CERT_WIDTH;
  canvas.height = CERT_HEIGHT;
  const ctx = canvas.getContext('2d');

  // Background
  ctx.fillStyle = '#0f0f2a';
  ctx.fillRect(0, 0, CERT_WIDTH, CERT_HEIGHT);

  // Inner background
  ctx.fillStyle = '#151535';
  ctx.fillRect(30, 30, CERT_WIDTH - 60, CERT_HEIGHT - 60);

  // Gold border (double line)
  ctx.strokeStyle = '#FFD700';
  ctx.lineWidth = 4;
  ctx.strokeRect(20, 20, CERT_WIDTH - 40, CERT_HEIGHT - 40);
  ctx.strokeStyle = '#FFD70088';
  ctx.lineWidth = 2;
  ctx.strokeRect(40, 40, CERT_WIDTH - 80, CERT_HEIGHT - 80);

  // Corner decorations
  drawCornerStar(ctx, 55, 55);
  drawCornerStar(ctx, CERT_WIDTH - 55, 55);
  drawCornerStar(ctx, 55, CERT_HEIGHT - 55);
  drawCornerStar(ctx, CERT_WIDTH - 55, CERT_HEIGHT - 55);

  // Decorative line under raffle name
  const cx = CERT_WIDTH / 2;

  // Raffle name (header)
  ctx.fillStyle = '#FFD700';
  ctx.font = 'bold 28px "Arial Black", Impact, sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText(raffleName.toUpperCase(), cx, 100);

  // Decorative divider
  drawDivider(ctx, cx, 140, 300);

  // "Certificate of Award" / "Winner"
  ctx.fillStyle = '#FFFFFF';
  ctx.font = '20px "Arial Black", Impact, sans-serif';
  ctx.letterSpacing = '4px';
  ctx.fillText('CERTIFICATE OF WINNING', cx, 185);

  // "This certifies that"
  ctx.fillStyle = '#888899';
  ctx.font = '18px -apple-system, "Segoe UI", Roboto, sans-serif';
  ctx.fillText('This certifies that', cx, 260);

  // Winner name (large, gold)
  ctx.fillStyle = '#FFD700';
  ctx.font = 'bold 52px "Arial Black", Impact, sans-serif';
  // Truncate if too long
  let displayName = winnerName;
  while (ctx.measureText(displayName).width > CERT_WIDTH - 160 && displayName.length > 3) {
    displayName = displayName.slice(0, -4) + '...';
  }
  ctx.fillText(displayName, cx, 330);

  // Decorative divider
  drawDivider(ctx, cx, 370, 200);

  // "has won"
  ctx.fillStyle = '#888899';
  ctx.font = '18px -apple-system, "Segoe UI", Roboto, sans-serif';
  ctx.fillText('has won', cx, 420);

  // Prize name (large, pink)
  ctx.fillStyle = '#FF1493';
  ctx.font = 'bold 40px "Arial Black", Impact, sans-serif';
  let displayPrize = prizeName;
  while (ctx.measureText(displayPrize).width > CERT_WIDTH - 160 && displayPrize.length > 3) {
    displayPrize = displayPrize.slice(0, -4) + '...';
  }
  ctx.fillText(displayPrize, cx, 485);

  // Decorative divider
  drawDivider(ctx, cx, 530, 300);

  // Stars decoration
  ctx.fillStyle = '#FFD700';
  ctx.font = '24px sans-serif';
  ctx.fillText('\u2605  \u2605  \u2605', cx, 580);

  // Date
  ctx.fillStyle = '#888899';
  ctx.font = '16px -apple-system, "Segoe UI", Roboto, sans-serif';
  const dateStr = new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  ctx.fillText(dateStr, cx, 640);

  // Footer text
  ctx.fillStyle = '#444466';
  ctx.font = '12px -apple-system, "Segoe UI", Roboto, sans-serif';
  ctx.fillText('Generated by Raffle Winner Picker', cx, CERT_HEIGHT - 60);

  return canvas;
}

function drawCornerStar(ctx, x, y) {
  ctx.save();
  ctx.fillStyle = '#FFD700';
  ctx.font = '20px sans-serif';
  ctx.textAlign = 'center';
  ctx.textBaseline = 'middle';
  ctx.fillText('\u2605', x, y);
  ctx.restore();
}

function drawDivider(ctx, x, y, width) {
  ctx.save();
  ctx.strokeStyle = '#FFD70066';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(x - width / 2, y);
  ctx.lineTo(x + width / 2, y);
  ctx.stroke();

  // Center diamond
  ctx.fillStyle = '#FFD700';
  ctx.beginPath();
  ctx.moveTo(x, y - 4);
  ctx.lineTo(x + 4, y);
  ctx.lineTo(x, y + 4);
  ctx.lineTo(x - 4, y);
  ctx.closePath();
  ctx.fill();
  ctx.restore();
}

/**
 * Download a certificate as PNG.
 */
export function downloadCertificate({ raffleName, winnerName, prizeName, date }) {
  const canvas = renderCertificate({ raffleName, winnerName, prizeName, date });
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `certificate-${winnerName.replace(/[^a-zA-Z0-9]/g, '_')}.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 'image/png');
}

/**
 * Download all certificates.
 */
export function downloadAllCertificates(raffleName, winners) {
  winners.forEach((w, i) => {
    // Stagger downloads to avoid browser blocking
    setTimeout(() => {
      downloadCertificate({
        raffleName,
        winnerName: w.name,
        prizeName: w.prize,
        date: w.timestamp,
      });
    }, i * 500);
  });
}
